In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define Vocabulary size
voc_size = 10000


In [5]:
## One hot Representation 
one_hot_represent = [one_hot(words, voc_size) for words in sent]
one_hot_represent #shows only indexes of the words

[[7451, 3192, 6643, 8751],
 [7451, 3192, 6643, 4968],
 [7451, 4210, 6643, 5914],
 [6355, 6107, 1678, 8495, 9991],
 [2905, 7451, 9845, 6643, 6412],
 [2086, 1261, 708, 8495]]

In [6]:
## Word embeddeing reprentation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences ## Adds zeros to adjust sentence length
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np
sent_length = 8 #To make all sentences same length as NN needs all input should be of same length
embedded_doc = pad_sequences(one_hot_represent, padding='pre',maxlen=sent_length)
embedded_doc

array([[   0,    0,    0,    0, 7451, 3192, 6643, 8751],
       [   0,    0,    0,    0, 7451, 3192, 6643, 4968],
       [   0,    0,    0,    0, 7451, 4210, 6643, 5914],
       [   0,    0,    0, 6355, 6107, 1678, 8495, 9991],
       [   0,    0,    0, 2905, 7451, 9845, 6643, 6412],
       [   0,    0,    0,    0, 2086, 1261,  708, 8495]], dtype=int32)

In [8]:
## Feature representation
dim = 10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam', 'mse')

m:\Learning_Workspace\AI\NLP-Concepts\nlp\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step


array([[[-0.01129348, -0.03975831, -0.02602074,  0.00657086,
          0.00799757,  0.03782514, -0.00694393, -0.00708745,
         -0.04075326,  0.02015258],
        [-0.01129348, -0.03975831, -0.02602074,  0.00657086,
          0.00799757,  0.03782514, -0.00694393, -0.00708745,
         -0.04075326,  0.02015258],
        [-0.01129348, -0.03975831, -0.02602074,  0.00657086,
          0.00799757,  0.03782514, -0.00694393, -0.00708745,
         -0.04075326,  0.02015258],
        [-0.01129348, -0.03975831, -0.02602074,  0.00657086,
          0.00799757,  0.03782514, -0.00694393, -0.00708745,
         -0.04075326,  0.02015258],
        [ 0.04775156, -0.03434551, -0.00749683,  0.04683824,
          0.04588855, -0.00390245,  0.01429996,  0.01905813,
         -0.04142509, -0.01652865],
        [ 0.0134439 , -0.03218918, -0.01786115, -0.02173207,
          0.04494273, -0.00992508, -0.01575855,  0.03890857,
          0.04008087,  0.04398746],
        [ 0.02310357,  0.02118397,  0.01782031, -0.0

In [12]:
embedded_doc[0]

array([   0,    0,    0,    0, 7451, 3192, 6643, 8751], dtype=int32)

In [ ]:
'''word embedding for first sentence are[ 0.03219375,  0.00858467,  0.03947996, -0.03490381,
         -0.01985881,  0.01445988,  0.00234581,  0.01317957,
         -0.02436519, -0.03215386]'''